config_version: 1.0

model:
  architecture: all-1-screlu
  hidden_size: 64
  qa: 255
  qb: 64
  output_scale: 400
  wdl_scale: 306.64

training_options:
  train_path: dataset/eval/train_clean
  test_path: dataset/eval/test_clean

  superbatches: 3000
  lr_init: 0.001
  lr_final: 0.00000243
  batch_size: 16384
  lambda: 0.4
  patience: 10
  save_freq: 50
