config_version: 1.0

model:
  architecture: all-1-screlu
  hidden_size: 64
  qa: 255
  qb: 64
  output_scale: 400
  wdl_scale: 258.0

training_options:
  train_path: dataset/eval/train_clean
  test_path: dataset/eval/test

  superbatches: 500
  lr_init: 0.001
  lr_final: 0.00000243
  patience: 10
  batch_size: 32

  save_freq: 4
